### ISSUE TITLE
你可能已经遗忘的 CSS 选择器用法

### ISSUE THREAD

**Issue by Mcbai** [Mcbai/Blog#11]
这是一篇由一个 CSS 选择器引发的文章，讲真，从来没想过会写一篇关于 CSS 选择器的文章。

事先声明，这篇文章是对一些基础的回顾，没有什么新东西或者黑科技。
如果你早已将这些 CSS 基础烂熟于胸，大可直接 Ctrl + w。
如果你跟我一样对这些基础有些遗忘，那么可以尝试看下去。

事情的经过是这样的......

那是一个月黑风高的夜晚，我和同事一边愉快地加着班，一边悲愤地打着农药。趁着被敌方后羿shutdown的间隙，我花了 20 秒敲下了一行代码，等待页面热更新，查看效果，perfect！一切正常！

然鹅，正当我快要复活的时候，列表也滚到底了，卧槽！！最后一个 Item 样式出现了问题，但是时间已经来不及，快要复活了......以后可以写一篇博客叫《论敌方打野与我方打野》。

虽然我只花了一分钟就换了个方式来解决这个问题，但彻底把原来的问题搞明白却花了我差不多一个小时。

先给大家重现一下问题：

### 之前正常运行的代码

``` HTML
	<div class="list">
		<div class="item">我是第一个item</div>
		<div class="item">我是第二个item</div>
		<div class="item">我是第三个item</div>
		<div class="item">我是第四个item</div>
		<div class="item">我是第五个item</div>
	</div>
```

``` CSS
	.list {
		padding: 15px;
		background-color: #eee;
	}
	.item {
		margin-bottom: 15px;
		border-radius: 4px;
		background-color: #fff;
	}
	.item:last-child {
		margin-bottom: 50px;
	}
```

### 有问题的代码

``` HTML
	<div class="list">
		<div class="item">我是第一个item</div>
		<div class="item">我是第二个item</div>
		<div class="item">我是第三个item</div>
		<div class="item">我是第四个item</div>
		<div class="item">我是第五个item</div>
		<div class="dialog">......</div>
	</div>
```

``` CSS
	.list {
		padding: 15px;
		background-color: #eee;
	}
	.item {
		margin-bottom: 15px;
		border-radius: 4px;
		background-color: #fff;
	}
	.item:last-child {
		margin-bottom: 50px;
	}
```

发现问题在哪了吗？
如果你一眼看出问题所在，并确切的知道原因，那么恭喜你，CSS 基础还是挺扎实的。
如果你发现了问题但不确定原因或者压根都没找到问题，那么也同样恭喜你，至少看见了这篇文章。

## :last-child

通常用法：`element:last-child`

匹配 element 父元素及其父元素的子元素，中的最后一个 element 子元素。

> 注意：这里的 element 元素必须是其父元素下 **所有元素** 的最后一个子元素才有效。

例子：
```HTML
	<div class="list">
		<div class="item">我是第一个item</div>
		<div class="item">我是第二个item</div>
		<div class="item">我是第三个item</div>
		<div class="box">
			<div class="item">穿插一个盒子item</div>
			<div class="item">穿插两个盒子item</div>
			<div class="item">穿插三个盒子item</div>
		</div>
		<div class="item">我是第四个item</div>
		<div class="item">我是最后一个item，但不是最后一个子元素</div>
		<div class="haha">我才是最后一个子元素</div>
	</div>
```

```CSS
	.list {
		padding: 15px;
		background-color: #eee;
	}
	.item {
		margin-bottom: 15px;
		border-radius: 4px;
		background-color: green;
	}
	.item:last-child {
		background-color: red;
	}
	.box {
		margin-left: 50px;
	}
	.haha {
		background-color: yellow;
	}
```

![image](https://user-images.githubusercontent.com/12459860/37600482-6edb5a4c-2bc2-11e8-8a11-3396d55c0c5c.png)

`:first-child` 选择器与它用法一样

## :last-of-type

通常用法：`element:last-of-type`

匹配 element 父元素下及其父元素的子元素，中的最后一个 element 子元素。

> 注意：这里的 element 元素只要是其父元素下的 **所有 element 元素** 中的最后一个就可以。
