### ISSUE TITLE
你可能不清楚的 CSS 选择器用法（二）

### ISSUE THREAD

**Issue by Mcbai** [Mcbai/Blog#12]
## 子元素选择器

用法：parent > child

子元素选择器通过 `>` 符连接两个元素，两个元素是严格的父子关系。

例子：

```html
  <div class="parent">
    <p class="child">我是子元素.child</p>
    <p class="child">我是子元素.child</p>
    <div class="box">
      <p class="child">我是孙子元素.child</p>
    </div>
  </div>
```

```css
.parent > .child {
  color: #f23;
}
```
